
import React from 'react';
import { LoadingSpinner, ErrorIcon, ImageIcon, FullScreenIcon } from './icons';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
  onImageClick: (url: string) => void;
}

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error, onImageClick }) => {
  
  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex flex-col items-center justify-center gap-3 text-primary animate-pulse">
          <LoadingSpinner />
          <p className="text-sm font-mono tracking-widest uppercase">Synthesizing...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="flex flex-col items-center justify-center gap-3 text-error p-4 text-center">
          <ErrorIcon />
          <p className="font-bold tracking-wide">Generation Failed</p>
          <p className="font-mono text-xs max-w-xs opacity-80">{error}</p>
        </div>
      );
    }
    
    if (imageUrl) {
        return (
            <div 
              className="w-full h-full relative group cursor-pointer overflow-hidden rounded-lg"
              onClick={() => onImageClick(imageUrl)}
            >
                <img 
                    src={imageUrl} 
                    alt="Generated by AI" 
                    className="w-full h-full object-contain bg-black/5 transition-all duration-300 group-hover:scale-105" 
                />
                <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                    <div className="p-3 bg-black/50 backdrop-blur-sm rounded-full text-white">
                      <FullScreenIcon />
                    </div>
                </div>
            </div>
        );
    }
    
    return (
      <div className="flex flex-col items-center justify-center gap-4 text-subtext">
        <ImageIcon />
        <p className="text-sm font-medium tracking-wide">Awaiting Input</p>
      </div>
    );
  };

  return (
    <div className="w-full aspect-square max-w-lg bg-mantle border border-surface0 rounded-xl flex items-center justify-center p-2 shadow-sm transition-all duration-300">
        <div className="w-full h-full rounded-lg overflow-hidden flex items-center justify-center bg-base/50 border border-surface0/50">
            {renderContent()}
        </div>
    </div>
  );
};
