import React from 'react';
import { LoadingSpinner, ErrorIcon, ImageIcon, FullScreenIcon } from './icons';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
  onImageClick: (url: string) => void;
}

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error, onImageClick }) => {
  
  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex flex-col items-center justify-center gap-4 text-cyan-300">
          <LoadingSpinner />
          <p className="text-lg animate-pulse tracking-widest">TRANSMITTING DATA...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="flex flex-col items-center justify-center gap-4 text-red-400">
          <ErrorIcon />
          <p className="text-lg font-semibold tracking-wider">SYSTEM ERROR</p>
          <p className="text-center font-mono text-sm">{error}</p>
        </div>
      );
    }
    
    if (imageUrl) {
        return (
            <div 
              className="w-full h-full p-1 bg-black/50 rounded-md shadow-inner group relative cursor-pointer"
              onClick={() => onImageClick(imageUrl)}
            >
                <img 
                    src={imageUrl} 
                    alt="Generated by AI" 
                    className="w-full h-full object-contain rounded-sm transition-all duration-300 group-hover:opacity-50" 
                />
                <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300 rounded-lg">
                    <div className="p-4 bg-black/70 rounded-full">
                      <FullScreenIcon />
                    </div>
                </div>
            </div>
        );
    }
    
    return (
      <div className="flex flex-col items-center justify-center gap-4 text-gray-600">
        <ImageIcon />
        <p className="text-lg tracking-wider">Awaiting visual data...</p>
      </div>
    );
  };

  return (
    <div className="w-full aspect-square bg-black/30 border-2 border-cyan-500/30 rounded-lg flex items-center justify-center p-4 transition-all duration-300 shadow-[0_0_15px_rgba(0,187,255,0.15)]">
        {renderContent()}
    </div>
  );
};
