
import React from 'react';
import { LoadingSpinner, ErrorIcon, MagicWandIcon, FullScreenIcon, ArrowDownWideIcon } from './icons';

interface ImageDisplayProps {
  imageUrl: string | null;
  isLoading: boolean;
  error: string | null;
  onImageClick: (url: string) => void;
}

export const ImageDisplay: React.FC<ImageDisplayProps> = ({ imageUrl, isLoading, error, onImageClick }) => {
  
  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex flex-col items-center justify-center gap-3 text-primary animate-pulse">
          <LoadingSpinner />
          <p className="text-sm font-mono tracking-widest uppercase">Synthesizing...</p>
        </div>
      );
    }

    if (error) {
      return (
        <div className="flex flex-col items-center justify-center gap-3 text-error p-4 text-center">
          <ErrorIcon />
          <p className="font-bold tracking-wide">Generation Failed</p>
          <p className="font-mono text-xs max-w-xs opacity-80">{error}</p>
        </div>
      );
    }
    
    if (imageUrl) {
        return (
            <div 
              className="w-full h-full relative group cursor-pointer overflow-hidden rounded-lg"
              onClick={() => onImageClick(imageUrl)}
            >
                <img 
                    src={imageUrl} 
                    alt="Generated by AI" 
                    className="w-full h-full object-contain bg-black/5 transition-all duration-300 group-hover:scale-105" 
                />
                <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-center justify-center">
                    <div className="p-3 bg-black/50 backdrop-blur-sm rounded-full text-white">
                      <FullScreenIcon />
                    </div>
                </div>
            </div>
        );
    }
    
    return (
      <div className="flex flex-col items-center justify-center h-full w-full relative p-6 text-center select-none">
        {/* Center Content */}
        <div className="flex flex-col items-center gap-4 opacity-70">
          <div className="p-4 rounded-full bg-surface1/20 text-primary mb-2">
             <MagicWandIcon className="w-12 h-12 sm:w-16 sm:h-16" />
          </div>
          <h3 className="text-xl font-semibold text-text tracking-tight">Ready to Imagine?</h3>
          <p className="text-sm text-subtext max-w-xs leading-relaxed font-light">
             Enter a prompt below to bring your ideas to life.
          </p>
        </div>

        {/* Bottom Arrow */}
        <div className="absolute bottom-6 flex flex-col items-center animate-bounce text-subtext opacity-60">
            <ArrowDownWideIcon className="w-6 h-6" />
        </div>
      </div>
    );
  };

  return (
    <div className="w-full aspect-square max-w-lg bg-mantle border border-surface0 rounded-xl flex items-center justify-center p-2 shadow-sm transition-all duration-300">
        <div className="w-full h-full rounded-lg overflow-hidden flex items-center justify-center bg-base/50 border border-surface0/50">
            {renderContent()}
        </div>
    </div>
  );
};
